export const APP_COPY = {
  ru: {
    eyebrow: "Smart Campus",
    title: "Навигация и сервисы кампуса",
    subtitle:
      "Один рабочий экран для маршрутов, сервисов и учебных точек без перегруженных наложений.",
    searchHint:
      "Поиск работает по аудиториям, библиотеке, столовой, сервисному центру и лабораториям.",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Тёмная",
    localeRu: "Русский",
    localeKk: "Қазақша",
    localeEn: "English",
    modes: {
      outdoor: "Кампус",
      indoor: "Корпус",
      route: "Маршрут",
    },
    panels: {
      navigator: "Навигация",
      places: "Подборки",
      services: "Сервисы",
      details: "Детали",
    },
    mapTitle: "Карта корпуса",
    campusMap: "Карта кампуса",
    currentFloor: "Текущий этаж",
    returnToCampus: "К кампусу",
    quickRoutes: "Быстрые маршруты",
    quickRoutesText:
      "Популярные точки текущего этажа. Нажатие сразу строит маршрут.",
    accessible: "Без лестниц",
    accessibleHint: "Лифт и широкие проходы",
    routeBuilder: "Конструктор маршрута",
    myPoint: "Моя точка",
    buildRoute: "Построить маршрут",
    clear: "Сбросить",
    start: "Старт",
    destination: "Точка назначения",
    chooseStart: "Задайте старт",
    chooseDestination: "Выберите точку назначения",
    collectionsTitle: "Подборки точек",
    collectionsText: "Открывайте одну подборку за раз, чтобы не перегружать панель.",
    servicesTitle: "Сервисы кампуса",
    servicesText:
      "Все сервисы открываются по нажатию. В каждый момент виден только выбранный блок.",
    detailsTitle: "Детали",
    detailsText:
      "Здесь открываются карточки помещений и пошаговый маршрут, когда вы их выбираете.",
    emptyDetailsTitle: "Ничего не выбрано",
    emptyDetailsText:
      "Кликните по помещению на карте, выполните поиск или постройте маршрут.",
    nearbyTitle: "Вы рядом с кампусом",
    nearbyText:
      "Когда будете внутри корпуса, переключайтесь на внутреннюю карту и продолжайте навигацию по этажам.",
    openIndoor: "Перейти к этажам",
    routeStandard: "Стандартный маршрут",
    routeAccessible: "Безбарьерный маршрут",
    routeSummary: "Маршрут готов",
    routeSummaryText: "Шаги и подробности открыты в панели «Детали».",
    routeOnMap: "Маршрут на карте",
    userLegend: "Моя точка",
    destinationLegend: "Точка назначения",
    lineLegend: "Линия маршрута",
    geoUnsupported: "Браузер не поддерживает геолокацию.",
    geoDenied: "Не удалось получить текущую геопозицию.",
  },
  kk: {
    eyebrow: "Smart Campus",
    title: "Кампус навигациясы мен сервистері",
    subtitle:
      "Маршруттар, сервистер және оқу нүктелері бір экранда, артық қабаттасуларсыз.",
    searchHint:
      "Іздеу аудиториялар, кітапхана, асхана, қызмет орталығы және зертханалар бойынша жұмыс істейді.",
    language: "Тіл",
    theme: "Тақырып",
    light: "Жарық",
    dark: "Қараңғы",
    localeRu: "Русский",
    localeKk: "Қазақша",
    localeEn: "English",
    modes: {
      outdoor: "Кампус",
      indoor: "Корпус",
      route: "Маршрут",
    },
    panels: {
      navigator: "Навигация",
      places: "Топтамалар",
      services: "Сервистер",
      details: "Детальдар",
    },
    mapTitle: "Корпус картасы",
    campusMap: "Кампус картасы",
    currentFloor: "Қазіргі қабат",
    returnToCampus: "Кампусқа оралу",
    quickRoutes: "Жылдам маршруттар",
    quickRoutesText:
      "Ағымдағы қабаттағы танымал нүктелер. Батырма бірден маршрут құрады.",
    accessible: "Баспалдақсыз",
    accessibleHint: "Лифт пен кең өткелдер",
    routeBuilder: "Маршрут құрастыру",
    myPoint: "Менің нүктем",
    buildRoute: "Маршрут құру",
    clear: "Тазарту",
    start: "Бастау",
    destination: "Бару нүктесі",
    chooseStart: "Бастау нүктесін таңдаңыз",
    chooseDestination: "Бару нүктесін таңдаңыз",
    collectionsTitle: "Нүктелер топтамасы",
    collectionsText:
      "Панельді шамадан тыс жүктемеу үшін бір топтаманы ғана ашыңыз.",
    servicesTitle: "Кампус сервистері",
    servicesText:
      "Барлық сервистер батырмамен ашылады. Бір уақытта тек таңдалған блок көрінеді.",
    detailsTitle: "Детальдар",
    detailsText:
      "Мұнда бөлме карталары мен қадамдық маршрут тек сіз таңдағанда ашылады.",
    emptyDetailsTitle: "Ештеңе таңдалмады",
    emptyDetailsText:
      "Картадағы бөлмені таңдаңыз, іздеу жасаңыз немесе маршрут құрыңыз.",
    nearbyTitle: "Сіз кампусқа жақынсыз",
    nearbyText:
      "Корпус ішіне кіргенде ішкі картаға ауысып, қабаттар бойынша навигацияны жалғастырыңыз.",
    openIndoor: "Қабаттарға өту",
    routeStandard: "Қалыпты маршрут",
    routeAccessible: "Кедергісіз маршрут",
    routeSummary: "Маршрут дайын",
    routeSummaryText: "Қадамдар мен толық ақпарат «Детальдар» панелінде ашылады.",
    routeOnMap: "Картадағы маршрут",
    userLegend: "Менің нүктем",
    destinationLegend: "Бару нүктесі",
    lineLegend: "Маршрут сызығы",
    geoUnsupported: "Браузер геолокацияны қолдамайды.",
    geoDenied: "Ағымдағы геопозицияны алу мүмкін болмады.",
  },
  en: {
    eyebrow: "Smart Campus",
    title: "Campus navigation and services",
    subtitle:
      "One focused workspace for routes, services, and study points without overloaded map layers.",
    searchHint:
      "Search works across rooms, the library, cafeteria, service center, and labs.",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    localeRu: "Русский",
    localeKk: "Қазақша",
    localeEn: "English",
    modes: {
      outdoor: "Campus",
      indoor: "Building",
      route: "Route",
    },
    panels: {
      navigator: "Navigation",
      places: "Collections",
      services: "Services",
      details: "Details",
    },
    mapTitle: "Building map",
    campusMap: "Campus map",
    currentFloor: "Current floor",
    returnToCampus: "Back to campus",
    quickRoutes: "Quick routes",
    quickRoutesText:
      "Popular points on the current floor. Tap once to build a route.",
    accessible: "No stairs",
    accessibleHint: "Elevator and wide corridors",
    routeBuilder: "Route builder",
    myPoint: "My point",
    buildRoute: "Build route",
    clear: "Clear",
    start: "Start",
    destination: "Destination",
    chooseStart: "Set start",
    chooseDestination: "Choose destination",
    collectionsTitle: "Point collections",
    collectionsText: "Open one collection at a time to keep the panel readable.",
    servicesTitle: "Campus services",
    servicesText:
      "All services open on demand. Only the selected block is visible at once.",
    detailsTitle: "Details",
    detailsText:
      "Room cards and step-by-step routes appear here after you select them.",
    emptyDetailsTitle: "Nothing selected",
    emptyDetailsText:
      "Click a room on the map, use search, or build a route.",
    nearbyTitle: "You are near campus",
    nearbyText:
      "When you are inside the building, switch to the indoor map and continue floor navigation.",
    openIndoor: "Open floors",
    routeStandard: "Standard route",
    routeAccessible: "Accessible route",
    routeSummary: "Route ready",
    routeSummaryText: "Steps and details are open in the Details panel.",
    routeOnMap: "Route on map",
    userLegend: "My point",
    destinationLegend: "Destination",
    lineLegend: "Route line",
    geoUnsupported: "Your browser does not support geolocation.",
    geoDenied: "Could not get the current location.",
  },
} as const;
