export const APP_COPY = {
  ru: {
    eyebrow: "Smart Campus",
    title: "Навигация и сервисы кампуса",
    subtitle:
      "Один рабочий экран для маршрутов, сервисов и учебных точек без перегруженных наложений.",
    searchHint:
      "Поиск работает по аудиториям, библиотеке, столовой, сервисному центру и лабораториям.",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Тёмная",
    localeRu: "Русский",
    localeKk: "Қазақша",
    modes: {
      outdoor: "Кампус",
      indoor: "Корпус",
      route: "Маршрут",
    },
    panels: {
      navigator: "Навигация",
      places: "Подборки",
      services: "Сервисы",
      details: "Детали",
    },
    mapTitle: "Карта корпуса",
    campusMap: "Карта кампуса",
    currentFloor: "Текущий этаж",
    returnToCampus: "К кампусу",
    quickRoutes: "Быстрые маршруты",
    quickRoutesText:
      "Популярные точки текущего этажа. Нажатие сразу строит маршрут.",
    accessible: "Без лестниц",
    accessibleHint: "Лифт и широкие проходы",
    routeBuilder: "Конструктор маршрута",
    myPoint: "Моя точка",
    buildRoute: "Построить маршрут",
    clear: "Сбросить",
    start: "Старт",
    destination: "Точка назначения",
    chooseStart: "Задайте старт",
    chooseDestination: "Выберите точку назначения",
    collectionsTitle: "Подборки точек",
    collectionsText: "Открывайте одну подборку за раз, чтобы не перегружать панель.",
    servicesTitle: "Сервисы кампуса",
    servicesText:
      "Все сервисы открываются по нажатию. В каждый момент виден только выбранный блок.",
    detailsTitle: "Детали",
    detailsText:
      "Здесь открываются карточки помещений и пошаговый маршрут, когда вы их выбираете.",
    emptyDetailsTitle: "Ничего не выбрано",
    emptyDetailsText:
      "Кликните по помещению на карте, выполните поиск или постройте маршрут.",
    nearbyTitle: "Вы рядом с кампусом",
    nearbyText:
      "Когда будете внутри корпуса, переключайтесь на внутреннюю карту и продолжайте навигацию по этажам.",
    openIndoor: "Перейти к этажам",
    routeStandard: "Стандартный маршрут",
    routeAccessible: "Безбарьерный маршрут",
    routeSummary: "Маршрут готов",
    routeSummaryText: "Шаги и подробности открыты в панели «Детали».",
    routeOnMap: "Маршрут на карте",
    userLegend: "Моя точка",
    destinationLegend: "Точка назначения",
    lineLegend: "Линия маршрута",
    geoUnsupported: "Браузер не поддерживает геолокацию.",
    geoDenied: "Не удалось получить текущую геопозицию.",
  },
  kk: {
    eyebrow: "Smart Campus",
    title: "Кампус навигациясы мен сервистері",
    subtitle:
      "Маршруттар, сервистер және оқу нүктелері бір экранда, артық қабаттасуларсыз.",
    searchHint:
      "Іздеу аудиториялар, кітапхана, асхана, қызмет орталығы және зертханалар бойынша жұмыс істейді.",
    language: "Тіл",
    theme: "Тақырып",
    light: "Жарық",
    dark: "Қараңғы",
    localeRu: "Русский",
    localeKk: "Қазақша",
    modes: {
      outdoor: "Кампус",
      indoor: "Корпус",
      route: "Маршрут",
    },
    panels: {
      navigator: "Навигация",
      places: "Топтамалар",
      services: "Сервистер",
      details: "Детальдар",
    },
    mapTitle: "Корпус картасы",
    campusMap: "Кампус картасы",
    currentFloor: "Қазіргі қабат",
    returnToCampus: "Кампусқа оралу",
    quickRoutes: "Жылдам маршруттар",
    quickRoutesText:
      "Ағымдағы қабаттағы танымал нүктелер. Батырма бірден маршрут құрады.",
    accessible: "Баспалдақсыз",
    accessibleHint: "Лифт пен кең өткелдер",
    routeBuilder: "Маршрут құрастыру",
    myPoint: "Менің нүктем",
    buildRoute: "Маршрут құру",
    clear: "Тазарту",
    start: "Бастау",
    destination: "Бару нүктесі",
    chooseStart: "Бастау нүктесін таңдаңыз",
    chooseDestination: "Бару нүктесін таңдаңыз",
    collectionsTitle: "Нүктелер топтамасы",
    collectionsText:
      "Панельді шамадан тыс жүктемеу үшін бір топтаманы ғана ашыңыз.",
    servicesTitle: "Кампус сервистері",
    servicesText:
      "Барлық сервистер батырмамен ашылады. Бір уақытта тек таңдалған блок көрінеді.",
    detailsTitle: "Детальдар",
    detailsText:
      "Мұнда бөлме карталары мен қадамдық маршрут тек сіз таңдағанда ашылады.",
    emptyDetailsTitle: "Ештеңе таңдалмады",
    emptyDetailsText:
      "Картадағы бөлмені таңдаңыз, іздеу жасаңыз немесе маршрут құрыңыз.",
    nearbyTitle: "Сіз кампусқа жақынсыз",
    nearbyText:
      "Корпус ішіне кіргенде ішкі картаға ауысып, қабаттар бойынша навигацияны жалғастырыңыз.",
    openIndoor: "Қабаттарға өту",
    routeStandard: "Қалыпты маршрут",
    routeAccessible: "Кедергісіз маршрут",
    routeSummary: "Маршрут дайын",
    routeSummaryText: "Қадамдар мен толық ақпарат «Детальдар» панелінде ашылады.",
    routeOnMap: "Картадағы маршрут",
    userLegend: "Менің нүктем",
    destinationLegend: "Бару нүктесі",
    lineLegend: "Маршрут сызығы",
    geoUnsupported: "Браузер геолокацияны қолдамайды.",
    geoDenied: "Ағымдағы геопозицияны алу мүмкін болмады.",
  },
} as const;
